
```{r, message=FALSE, warning=FALSE}
### Consultoria ENEM 2016


#Pacotes
library(readr)
library(stringr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(treemapify)

# dados <- read_csv2('microdados_enem_2016.csv') |> filter(NU_ANO==2016,
#                                                         TP_ST_CONCLUSAO %in% c(1,2),
#                                                         SG_UF_RESIDENCIA %in% c('RJ','SP','MG','ES'),
#                                                         IN_TREINEIRO==0,
#                                                         TP_PRESENCA_LC==1,
#                                                         TP_PRESENCA_CH==1) |>
#   select(c(TP_COR_RACA,TP_SEXO,TP_ESCOLA,Q005,Q026,Q002,Q006,NU_IDADE,NU_NOTA_REDACAO, NU_NOTA_CN, NU_NOTA_CH, NU_NOTA_LC, NU_NOTA_MT,Q047))
# 
# write.csv(dados,'dados_enem.csv')
# 
# dados <- read_csv('dados_enem.csv')
# dados <- dados[,-1]
# 
# dados <- dados |> rename(R= NU_NOTA_REDACAO, CNT= NU_NOTA_CN, CHT= NU_NOTA_CH, LCT= NU_NOTA_LC,
#                      MT= NU_NOTA_MT,RACA = TP_COR_RACA,SEXO = TP_SEXO,ESCOLA = TP_ESCOLA,MORA = Q005,TRAB= Q026,ESCOL_MAE= Q002,IDADE= NU_IDADE,RENDA= Q006, EM=Q047) |> 
#   mutate(CNT= paste0(str_sub(CNT, 1, 3), ".", str_sub(CNT, 4, 4)),
#          CNT= as.numeric(CNT),
#          CHT= paste0(str_sub(CHT, 1, 3), ".", str_sub(CHT, 4, 4)),
#          CHT= as.numeric(CHT),
#          LCT= paste0(str_sub(LCT, 1, 3), ".", str_sub(LCT, 4, 4)),
#          LCT= as.numeric(LCT),
#          MT= paste0(str_sub(MT, 1, 3), ".", str_sub(MT, 4, 4)),
#          MT= as.numeric(MT),
#          FORMULA= (2*R + CNT + 2*CHT + LCT + MT)/7)

#dados <- na.omit(dados)
# write.csv(dados,'ENEM_dados.csv')
# 
# 
# dados <- read_csv('ENEM_dados.csv')
# dados <- dados[,-1]
####A0 ou B, ampla conc = 
####L1 ou A1, renda <= 1,5 SM e EM cursado em EP
####L2 ou A2, renda <= 1,5 SM, RACA sendo parda, indigena e preta e EM cursado em EP
####L5 ou A6, enda > 1,5 SM e EM cursado em EP
####L6 ou A7, renda > 1,5 SM , RACA sendo parda, indigena e preta e EM cursado em EP

# for (i in 1:dim(dados)[1]){
#   if (dados$RENDA[i]==c("A","B","C") & dados$EM[i]=="A"){
#     if (dados$RACA[i]==c(2, 3, 5)){
#       dados$A2[i] <- 1
#       dados$A1[i] <- 1
#       dados$B[i] <- 0
#     }else {
#       dados$A2[i] <- 0
#       dados$A1[i] <- 1
#       dados$B[i] <- 0
#       }
#   }else if (dados$RENDA[i]!=c("A","B","C") & dados$EM[i]=="A") {
#     if (dados$RACA[i]==c(2, 3, 5)){
#       dados$A6[i] <- 1
#       dados$A1[i] <- 0
#       dados$A7[i] <- 1
#       dados$B[i] <- 0
#     }else {
#       dados$A6[i] <- 1
#       dados$A7[i] <- 0
#       dados$B[i] <- 0
#     }
#   }else{
#     dados$B[i] <- 1
#     dados$A6[i] <- 0
#     dados$A7[i] <- 0
#     dados$A2[i] <- 0
#     dados$A1[i] <- 0
#   }
# 
# }
# write.csv(dados,'dados_ENEM.csv')


# dados <- read_csv('dados_ENEM.csv')
# dados <- dados[,-c(1,2)]

################################################################################################
# #raça
# dados$RACA<- ordered(dados$RACA,levels=c(0,1,2,3,4,5,6),
#                      labels=c("Não Declarado","Branco","Preta","Parda","Amarela","Indígena","Não dispõe da informação"))
# #sexo
# dados$SEXO<- ordered(dados$SEXO,levels=c("M","F"),
#                      labels=c("Masculino","Feminino"))
# #escola
# dados$ESCOLA <-ordered(dados$ESCOLA,levels=c(1,2,3,4),
#                        labels=c("Não Respondeu","Pública","Privada","Exterior"))
# #trabalho
# dados$TRAB <-ordered(dados$TRAB,levels=c("A","B","C"),
#                           labels=c("Não, nunca trabalhei.","Sim, já trabalhei, mas não estou trabalhando.","Sim, estou trabalhando."))
# #escolaridade da mãe
# dados$ESCOL_MAE <-ordered(dados$ESCOL_MAE,levels=c("A","B","C","D","E","F","G","H"),
#                        labels=c("Nunca estudou.","Não completou a 4ª série/5º ano do Ensino Fundamental.","Completou a 4ª série/5º ano, mas não completou a 8ª série/9º ano do Ensino Fundamental.","Completou a 8ª série/9º ano do Ensino Fundamental, mas não completou o Ensino Médio.","Completou o Ensino Médio, mas não completou a Faculdade.","Completou a Faculdade, mas não completou a Pós-graduação.","Completou a Pós-graduação.","Não sei."))
# #renda
# dados$RENDA <-ordered(dados$RENDA,levels=c("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q"),
#                           labels=c("Nenhuma renda.","Até R$ 880,00.","De R$ 880,01 até R$ 1.320,00.","De R$ 1.320,01 até R$ 1.760,00.","De R$ 1.760,01 até R$ 2.200,00.","De R$ 2.200,01 até R$ 2.640,00.","De R$ 2.640,01 até R$ 3.520,00.","De R$ 3.520,01 até R$ 4.400,00.","De R$ 4.400,01 até R$ 5.280,00.","De R$ 5.280,01 até R$ 6.160,00.","De R$ 6.160,01 até R$ 7.040,00.","De R$ 7.040,01 até R$ 7.920,00.","De R$ 7.920,01 até R$ 8.800,00.","De R$ 8.800,01 até R$ 10.560,00.","De R$ 10.560,01 até R$ 13.200,00.","De R$ 13.200,01 até R$ 17.600,00.","Mais de R$ 17.600,00."))
# #escola em que cursou o ensino médio
# dados$EM <-ordered(dados$EM,levels=c("A","B","C","D","E"),
#                       labels=c("Somente em escola pública.","Parte em escola pública e parte em escola privada sem bolsa de estudo integral.","Parte em escola pública e parte em escola privada com bolsa de estudo integral.","Somente em escola privada sem bolsa de estudo integral.","Somente em escola privada com bolsa de estudo integral."))

```

```{r}
# library(dplyr)
# 
# load("dados_enem.RData")
# base <- base_enem
# ## Criando grupos para classificar a classe de concorrência
# 
# base$indicador <- seq(from=1, to=length(base$RACA),by=1)
# 
# A1.1 <- filter(base, RENDA %in% c("A","B","C"),
#                EM == "A")
# A1.1 <- mutate(A1.1, A1=1)
# 
# A1.2 <- filter(base, !indicador %in% A1.1$indicador) 
# A1.2 <- mutate(A1.2, A1=0)
# 
# base <- rbind(A1.1,A1.2)
# 
# #---------------------------------------------------------------
# 
# A2.1 <- filter(base, RENDA %in% c("A","B","C"),
#                EM == "A",
#                RACA %in% c(2, 3, 5)) 
# A2.1 <- mutate(A2.1, A2=1)
# 
# A2.2 <- filter(base, !indicador %in% A2.1$indicador) 
# A2.2 <- mutate(A2.2, A2=0)
# 
# 
# base <- rbind(A2.1,A2.2)
# 
# #---------------------------------------------------------------
# 
# A6.1 <- filter(base, !RENDA %in% c("A","B","C"),
#                EM == "A")
# A6.1 <- mutate(A6.1, A6=1)
# 
# A6.2 <- filter(base, !indicador %in% A6.1$indicador)
# A6.2 <- mutate(A6.2, A6=0)
# 
# base <- rbind(A6.1,A6.2)
# 
# #---------------------------------------------------------------
# 
# A7.1 <- filter(base, !RENDA %in% c("A","B","C"),
#                EM == "A",
#                RACA %in% c(2, 3, 5))
# A7.1 <- mutate(A7.1, A7=1)
# 
# A7.2 <- filter(base, !indicador %in% A7.1$indicador)
# A7.2 <- mutate(A7.2, A7=0)
# 
# base <- rbind(A7.1,A7.2)
# 
# #---------------------------------------------------------------
# 
# B.1 <- filter(base, EM != "A")
# B.1 <- mutate(B.1, B=1)
# 
# B.2 <- filter(base, EM == "A")
# B.2 <- mutate(B.2, B=0)
# 
# base <- rbind(B.1,B.2)
# #---------------------------------------------------------------
# base <- arrange(base, by=indicador)
# 
# 
# ## Excluindo tudo que não será mais utilizado
# rm(A1.1,A1.2,A2.1,A2.2,A6.1,A6.2,A7.1,A7.2,B.1,B.2,base_enem)
# 
# ```
# 
# ```{r}
# ## Variável sobre situação de aprovação
# 
# b1ap <- base |> filter(B==1, FORMULA >= 661.34, R>=300, CNT>=300,CHT>=350,
#                        LCT>=300, MT>=250) |> 
#   mutate(Situação_B.1='Aprovado')
# 
# b1nc <- base |> filter(B==0) |> mutate(Situação_B.1='Não concorreu')
# 
# b1aux <- rbind(b1ap,b1nc)
# 
# b1na <- base |> filter(!indicador %in% b1aux$indicador) |> 
#   mutate(Situação_B.1='Não aprovado')
# 
# base <- rbind(b1aux,b1na)
# #------------------------------------------------------------------------------
# A1.1ap <- base |> filter(A1==1, A2==0, FORMULA >= 635.91, R>=300, CNT>=300,CHT>=350,
#                        LCT>=300, MT>=250) |> 
#   mutate(Situação_A1.1='Aprovado')
# 
# A1.1nc <- base |> filter(A1==0) |> mutate(Situação_A1.1='Não concorreu')
# 
# A1.1aux <- rbind(A1.1ap,A1.1nc)
# 
# A1.1na <- base |> filter(!indicador %in% A1.1aux$indicador) |> 
#   mutate(Situação_A1.1='Não aprovado')
# 
# base <- rbind(A1.1aux,A1.1na)
# #------------------------------------------------------------------------------
# A2.1ap <- base |> filter(A2==1, FORMULA >= 620.97, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A2.1='Aprovado')
# 
# A2.1nc <- base |> filter(A2==0) |> mutate(Situação_A2.1='Não concorreu')
# 
# A2.1aux <- rbind(A2.1ap,A2.1nc)
# 
# A2.1na <- base |> filter(!indicador %in% A2.1aux$indicador) |> 
#   mutate(Situação_A2.1='Não aprovado')
# 
# base <- rbind(A2.1aux,A2.1na)
# #------------------------------------------------------------------------------
# A6.1ap <- base |> filter(A6==1, A7==0, FORMULA >= 654.47, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A6.1='Aprovado')
# 
# A6.1nc <- base |> filter(A6==0) |> mutate(Situação_A6.1='Não concorreu')
# 
# A6.1aux <- rbind(A6.1ap,A6.1nc)
# 
# A6.1na <- base |> filter(!indicador %in% A6.1aux$indicador) |> 
#   mutate(Situação_A6.1='Não aprovado')
# 
# base <- rbind(A6.1aux,A6.1na)
# #------------------------------------------------------------------------------
# A7.1ap <- base |> filter(A7==1, FORMULA >= 629.21, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A7.1='Aprovado')
# 
# A7.1nc <- base |> filter(A7==0) |> mutate(Situação_A7.1='Não concorreu')
# 
# A7.1aux <- rbind(A7.1ap,A7.1nc)
# 
# A7.1na <- base |> filter(!indicador %in% A7.1aux$indicador) |> 
#   mutate(Situação_A7.1='Não aprovado')
# 
# base <- rbind(A7.1aux,A7.1na)
# #------------------------------------------------------------------------------
# ## B.2- 2º período
# B.2ap <- base |> filter(Situação_B.1=='Não aprovado', B==1, FORMULA >= 625.81, R>=300, CNT>=300,CHT>=350,
#                         LCT>=300, MT>=250) |> 
#   mutate(Situação_B.2='Aprovado')
# 
# B.2nc <- base |> filter(B==0 | Situação_B.1=='Aprovado') |> 
#   mutate(Situação_B.2='Não concorreu')
# 
# B.2aux <- rbind(B.2ap,B.2nc)
# 
# B.2na <- base |> filter(!indicador %in% B.2aux$indicador) |> 
#   mutate(Situação_B.2='Não aprovado')
# 
# base <- rbind(B.2aux,B.2na)
# #------------------------------------------------------------------------------
# ## A1.2- 2º período
# A1.2ap <- base |> filter(Situação_A1.1=='Não aprovado', A1==1, A2==0, FORMULA >= 612.20, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A1.2='Aprovado')
# 
# A1.2nc <- base |> filter(A1==0 | Situação_A1.1=='Aprovado') |> 
#   mutate(Situação_A1.2='Não concorreu')
# 
# A1.2aux <- rbind(A1.2ap,A1.2nc)
# 
# A1.2na <- base |> filter(!indicador %in% A1.2aux$indicador) |> 
#   mutate(Situação_A1.2='Não aprovado')
# 
# base <- rbind(A1.2aux,A1.2na)
# #------------------------------------------------------------------------------
# ## A2.2- 2º período
# A2.2ap <- base |> filter(Situação_A2.1=='Não aprovado', A2==1, FORMULA >= 588.24, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A2.2='Aprovado')
# 
# A2.2nc <- base |> filter(A2==0 | Situação_A2.1=='Aprovado') |> 
#   mutate(Situação_A2.2='Não concorreu')
# 
# A2.2aux <- rbind(A2.2ap,A2.2nc)
# 
# A2.2na <- base |> filter(!indicador %in% A2.2aux$indicador) |> 
#   mutate(Situação_A2.2='Não aprovado')
# 
# base <- rbind(A2.2aux,A2.2na)
# #------------------------------------------------------------------------------
# A6.2ap <- base |> filter(Situação_A6.1=='Não aprovado', A6==1, A7==0, FORMULA >= 619.39, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A6.2='Aprovado')
# 
# A6.2nc <- base |> filter(A6==0 | Situação_A6.1=='Aprovado') |> 
#   mutate(Situação_A6.2='Não concorreu')
# 
# A6.2aux <- rbind(A6.2ap,A6.2nc)
# 
# A6.2na <- base |> filter(!indicador %in% A6.2aux$indicador) |> 
#   mutate(Situação_A6.2='Não aprovado')
# 
# base <- rbind(A6.2aux,A6.2na)
# #------------------------------------------------------------------------------
# ## A7.2- 2º período
# A7.2ap <- base |> filter(Situação_A7.1=='Não aprovado', A7==1, FORMULA >= 586.84, R>=300, CNT>=300,CHT>=350,
#                          LCT>=300, MT>=250) |> 
#   mutate(Situação_A7.2='Aprovado')
# 
# A7.2nc <- base |> filter(A7==0 | Situação_A7.1=='Aprovado') |> 
#   mutate(Situação_A7.2='Não concorreu')
# 
# A7.2aux <- rbind(A7.2ap,A7.2nc)
# 
# A7.2na <- base |> filter(!indicador %in% A7.2aux$indicador) |> 
#   mutate(Situação_A7.2='Não aprovado')
# 
# base <- rbind(A7.2aux,A7.2na)
# #############################################################
# base <- arrange(base, indicador)
# 
# rm(list=setdiff(ls(), "base"))
# 
# base

```


```{r}
## Sumário para cada classe de concorrência
load("base_enem.RData")

#Dentro do Grupo A1
base |> 
  filter(RENDA %in% c("A","B","C"),
               EM == "A") |> 
  rename(RA1=R, CNTA1=CNT, CHTA1=CHT, LCTA1=LCT, MTA1=MT, FORMULAA1=FORMULA) |> 
  select(c(RA1, CNTA1, CHTA1, LCTA1, MTA1, FORMULAA1)) |> 
  summary()


#Fora do Grupo A1
base |> 
  filter(RENDA %in% c("A","B","C"),
               EM == "A") |> 
  rename(RFA1=R, CNTFA1=CNT, CHTFA1=CHT, LCTFA1=LCT, MTFA1=MT, FORMULAFA1=FORMULA) |> 
  select(c(RFA1, CNTFA1, CHTFA1, LCTFA1, MTFA1, FORMULAFA1)) |> 
  summary()

#---------------------------------------------------------------

#Dentro do Grupo A2
base |> 
  filter(RENDA %in% c("A","B","C"),
               EM == "A",
               RACA %in% c(2, 3, 5)) |> 
  rename(RA2=R, CNTA2=CNT, CHTA2=CHT, LCTA2=LCT, MTA2=MT, FORMULAA2=FORMULA) |> 
  select(c(RA2, CNTA2, CHTA2, LCTA2, MTA2, FORMULAA2)) |> 
  summary()

#Fora do Grupo A2
base |> 
  filter(!RENDA %in% c("A","B","C")|
               EM != "A"|
               !RACA %in% c(2, 3, 5)) |> 
  rename(RFA2=R, CNTFA2=CNT, CHTFA2=CHT, LCTFA2=LCT, MTFA2=MT, FORMULAFA2=FORMULA) |> 
  select(c(RFA2, CNTFA2, CHTFA2, LCTFA2, MTFA2, FORMULAFA2)) |> 
  summary() 

#---------------------------------------------------------------

#Dentro do Grupo A6
base |> 
  filter(!RENDA %in% c("A","B","C"),
               EM == "A") |> 
  rename(RA6=R, CNTA6=CNT, CHTA6=CHT, LCTA6=LCT, MTA6=MT, FORMULAA6=FORMULA) |> 
  select(c(RA6, CNTA6, CHTA6, LCTA6, MTA6, FORMULAA6)) |> 
  summary()

#Fora do Grupo A6
base |> 
  filter(RENDA %in% c("A","B","C")|
               EM != "A") |> 
  rename(RFA6=R, CNTFA6=CNT, CHTFA6=CHT, LCTFA6=LCT, MTFA6=MT, FORMULAFA6=FORMULA) |> 
  select(c(RFA6, CNTFA6, CHTFA6, LCTFA6, MTFA6, FORMULAFA6)) |> 
  summary()

#---------------------------------------------------------------

#Dentro do Grupo A7
base |> 
  filter(!RENDA %in% c("A","B","C"),
               EM == "A",
               RACA %in% c(2, 3, 5)) |> 
  rename(RA7=R, CNTA7=CNT, CHTA7=CHT, LCTA7=LCT, MTA7=MT, FORMULAA7=FORMULA) |> 
  select(c(RA7, CNTA7, CHTA7, LCTA7, MTA7, FORMULAA7)) |> 
  summary()

#Fora do Grupo A7
base |> 
  filter(RENDA %in% c("A","B","C")|
               EM != "A"|
               !RACA %in% c(2, 3, 5)) |> 
  rename(RFA7=R, CNTFA7=CNT, CHTFA7=CHT, LCTFA7=LCT, MTFA7=MT, FORMULAFA7=FORMULA) |> 
  select(c(RFA7, CNTFA7, CHTFA7, LCTFA7, MTFA7, FORMULAFA7)) |> 
  summary()

#---------------------------------------------------------------

#Dentro do Grupo B
base |> 
  filter(EM != "A") |> 
  rename(RB=R, CNTB=CNT, CHTB=CHT, LCTB=LCT, MTB=MT, FORMULAB=FORMULA) |> 
  select(c(RB, CNTB, CHTB, LCTB, MTB, FORMULAB)) |> 
  summary()

#Fora do Grupo B
base |> 
  filter(EM == "A") |> 
  rename(RFB=R, CNTFB=CNT, CHTFB=CHT, LCTFB=LCT, MTFB=MT, FORMULAFB=FORMULA) |> 
  select(c(RFB, CNTFB, CHTFB, LCTFB, MTFB, FORMULAFB)) |> 
  summary()

#---------------------------------------------------------------
```

```{r}
## Comparação segundo as Cotas B

g1 <- base |> 
  count(Situação_B.1) |> 
  ggplot(aes(x=Situação_B.1, y=n)) + 
  geom_bar(stat='identity',
           fill="red") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
  labs(x="Candidatos na ampla concorrência (B)", y="Frequência", 
       title="Situação dos candidatos na ampla concorrência (B) no 1º período") + theme_classic()

g2 <- base |> 
  count(Situação_B.2) |> 
  ggplot(aes(x=Situação_B.2, y=n)) + 
  geom_bar(stat='identity',
           fill="blue") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
    scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
    labs(x="Candidatos na ampla concorrência (B)", y="Frequência", 
       title="Situação dos candidatos na ampla concorrência (B) no 2º período") + theme_classic()

grid.arrange(g1, g2, ncol=2)
```

```{r}
## Comparação segundo as Cotas A1

g1 <- base |> 
  count(Situação_A1.1) |> 
  ggplot(aes(x=Situação_A1.1, y=n)) + 
  geom_bar(stat='identity',
           fill="red") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
  labs(x="Candidatos na ação afirmativa A1", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A1 no 1º período") + theme_classic()

g2 <- base |> 
  count(Situação_A1.2) |> 
  ggplot(aes(x=Situação_A1.2, y=n)) + 
  geom_bar(stat='identity',
           fill="blue") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
    scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
    labs(x="Candidatos na ação afirmativa A1", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A1 no 2º período") + theme_classic()

grid.arrange(g1, g2, ncol=2)
```

```{r}
## Comparação segundo as Cotas A2

g1 <- base |> 
  count(Situação_A2.1) |> 
  ggplot(aes(x=Situação_A2.1, y=n)) + 
  geom_bar(stat='identity',
           fill="red") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
  labs(x="Candidatos na ação afirmativa A2", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A2 no 1º período") + theme_classic()

g2 <- base |> 
  count(Situação_A2.2) |> 
  ggplot(aes(x=Situação_A2.2, y=n)) + 
  geom_bar(stat='identity',
           fill="blue") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
    scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
    labs(x="Candidatos na ação afirmativa A2", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A2 no 2º período") + theme_classic()

grid.arrange(g1, g2, ncol=2)
```


```{r}
## Comparação segundo as Cotas A6

g1 <- base |> 
  count(Situação_A6.1) |> 
  ggplot(aes(x=Situação_A6.1, y=n)) + 
  geom_bar(stat='identity',
           fill="red") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
  labs(x="Candidatos na ação afirmativa A6", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A6 no 1º período") + theme_classic()

g2 <- base |> 
  count(Situação_A6.2) |> 
  ggplot(aes(x=Situação_A6.2, y=n)) + 
  geom_bar(stat='identity',
           fill="blue") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
    scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
    labs(x="Candidatos na ação afirmativa A6", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A6 no 2º período") + theme_classic()

grid.arrange(g1, g2, ncol=2)
```

```{r}
## Comparação segundo as Cotas A7

g1 <- base |> 
  count(Situação_A7.1) |> 
  ggplot(aes(x=Situação_A7.1, y=n)) + 
  geom_bar(stat='identity',
           fill="red") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
  labs(x="Candidatos na ação afirmativa A7", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A7 no 1º período") + theme_classic()

g2 <- base |> 
  count(Situação_A7.2) |> 
  ggplot(aes(x=Situação_A7.2, y=n)) + 
  geom_bar(stat='identity',
           fill="blue") +
  geom_text(aes(label = n), 
            vjust=-0.5) +
    scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                     decimal.mark = ",")) +
    labs(x="Candidatos na ação afirmativa A7", y="Frequência", 
       title="Situação dos candidatos na ação afirmativa A7 no 2º período") + theme_classic()

grid.arrange(g1, g2, ncol=2)
```

```{r}
######################################################################################
##grafico de barras para raça dos candidatos
# Calculando o numero de pessoas em cada categoria de Raça
cont_RACA <- base |>
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
           Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
           Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") |>
  count(RACA)

# Visualizando o objeto criado
cont_RACA

cont_RACA$prop <- cont_RACA$n/sum(cont_RACA$n) * 100

cont_RACA$rotulo <- paste0(round(cont_RACA$prop,2), "%")

# Atividade
cont_RACA |> 
  mutate(RACA = ordered(RACA,levels=c(0,1,2,3,4,5,6),labels=c("Não Declarado","Branco","Preta","Parda","Amarela","Indígena","Não dispõe da informação"))) |> 
  ggplot(mapping = aes(x = reorder(RACA, -n),
                       y = n/sum(n))) +
  geom_bar(stat = "identity", fill = "Dark green", color = "Black") +
  geom_text(aes(label = rotulo), 
            vjust=-0.5) +
  labs(x = "Raça",y = "Porcentagem",
       title="Porcentagem de candidatos segundo a raça",
       subtitle="Dados referentes aos candidatos do ENEM 2016 aprovados em pedagogia na UFF em 2017") +   theme_classic() + scale_y_continuous(breaks = seq(0, 1, .2), 
                     label = scales::percent)

```

```{r}
######################################################################################
##grafico de barras para raça dos candidatos
# Calculando o numero de pessoas em cada categoria de Raça
cont_RACA <- base |>
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
           Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
           Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") |>
  count(RACA)

# Visualizando o objeto criado
cont_RACA

cont_RACA$prop <- cont_RACA$n/sum(cont_RACA$n) * 100

cont_RACA$rotulo <- paste0(round(cont_RACA$prop,2), "%")

# Atividade
cont_RACA |> 
  mutate(RACA = ordered(RACA,levels=c(0,1,2,3,4,5,6),labels=c("Não Declarado","Branco","Preta","Parda","Amarela","Indígena","Não dispõe da informação"))) |> 
  ggplot(mapping = aes(x = reorder(RACA, -n),
                       y = n/sum(n))) +
  geom_bar(stat = "identity", fill = "Dark green", color = "Black") +
  geom_text(aes(label = rotulo), 
            vjust=-0.5) +
  labs(x = "Raça",y = "Porcentagem",
       title="Porcentagem de candidatos segundo a raça",
       subtitle="Dados referentes aos candidatos do ENEM 2016 (população geral)") +   theme_classic() + scale_y_continuous(breaks = seq(0, 1, .2), 
                     label = scales::percent)

```

```{r}
#grafico de barras para situação de trabalho remunerado e tipo de escola que frequentou o ensino médio - para os aprovados em pedagogia

# criando um resumo do objeto base
perct_EM_TRAB <- base |> 
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
           Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
           Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") |> 
  group_by(EM, TRAB) |> 
  summarize(n = n()) |> 
  mutate(pct = n/sum(n),
         rotulo = scales::percent(pct))

# visualizando o objeto
perct_EM_TRAB

# adicionando os percentuais no gráfico
perct_EM_TRAB |>
  mutate(TRAB = ordered(TRAB,levels=c("A","B","C"), labels=c("Não, nunca trabalhei","Sim, já trabalhei, mas não estou trabalhando","Sim, estou trabalhando")), 
         EM= ordered(EM,levels=c("A","B","C","D","E"),
                    labels=c("Somente em escola pública","Parte em escola pública e \nparte em escola privada sem bolsa de estudo integral","Parte em escola pública e \nparte em escola privada com bolsa de estudo integral","Somente em escola privada \nsem bolsa de estudo integral","Somente em escola privada \ncom bolsa de estudo integral"))) |> 
  ggplot(mapping = aes(x = EM,
                       y = pct,
                       fill = factor(TRAB))) +
  geom_bar(stat = "identity",
           position = "fill") +
  scale_y_continuous(breaks = seq(0, 1, .2), 
                     label = percent) +
  geom_text(aes(label = rotulo), 
            size = 6, 
            position = position_stack(vjust = 0.5))  +
  scale_fill_brewer(palette = "Set1") +
  labs(x = "Tipo de escola que frequentou o ensino médio",
       y = "Proporção",
       fill = "Situação de trabalho",
       title="Perfil dos candidatos em relação ao tipo de escola que frequentou o ensino médio e situação de trabalho",
       subtitle="Dados referentes aos candidatos do ENEM 2016 aprovados em pedagogia na UFF em 2017") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2))

```

```{r}
#grafico de barras para situação de trabalho remunerado e tipo de escola que frequentou o ensino médio(população geral)

# criando um resumo do objeto base
perct_EM_TRAB <- base |> 
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
           Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
           Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") |> 
  group_by(EM, TRAB) |> 
  summarize(n = n()) |> 
  mutate(pct = n/sum(n),
         rotulo = scales::percent(pct))

# visualizando o objeto
perct_EM_TRAB

# adicionando os percentuais no gráfico
perct_EM_TRAB |>
  mutate(TRAB = ordered(TRAB,levels=c("A","B","C"), labels=c("Não, nunca trabalhei","Sim, já trabalhei, mas não estou trabalhando","Sim, estou trabalhando")), 
         EM= ordered(EM,levels=c("A","B","C","D","E"),
                    labels=c("Somente em escola pública","Parte em escola pública e \nparte em escola privada sem bolsa de estudo integral","Parte em escola pública e \nparte em escola privada com bolsa de estudo integral","Somente em escola privada \nsem bolsa de estudo integral","Somente em escola privada \ncom bolsa de estudo integral"))) |> 
  ggplot(mapping = aes(x = EM,
                       y = pct,
                       fill = factor(TRAB))) +
  geom_bar(stat = "identity",
           position = "fill") +
  scale_y_continuous(breaks = seq(0, 1, .2), 
                     label = percent) +
  geom_text(aes(label = rotulo), 
            size = 6, 
            position = position_stack(vjust = 0.5))  +
  scale_fill_brewer(palette = "Set1") +
  labs(x = "Tipo de escola que frequentou o ensino médio",
       y = "Proporção",
       fill = "Situação de trabalho",
       title="Perfil dos candidatos em relação ao tipo de escola que frequentou o ensino médio e situação de trabalho",
       subtitle="Dados referentes aos candidatos do ENEM 2016 (população geral)") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  scale_x_discrete(guide = guide_axis(n.dodge = 2))

```

```{r}
# #sexo geral
# base$SEXO<- ordered(base$SEXO,levels=c("M","F"),labels=c("Masculino","Feminino"))
# 
# sexo <- base |>
#   group_by(SEXO) |> 
#   summarise(n = n()) |>
#   mutate(prop = round(n*100/sum(n), 1),
#          rot.ypos = cumsum(prop) - 0.5*prop, 
#          rotulo = paste0(SEXO, "\n", round(prop,2), "%"))
# 
# # Criando um gráfico de setores com rótulos
# g20 <- ggplot(sexo, 
#              aes(x = "", 
#                  y = prop, 
#                  fill = order(SEXO))) +
#   geom_bar(width = 1, 
#            stat = "identity", 
#            color = "black",
#            fill = c("tomato", "#21908CFF")) +
#   geom_text(aes(y = rot.ypos, label = rotulo), 
#             color = "black") +
#   coord_polar("y", 
#               start = 0, 
#               direction = -1) +
#   theme_void() +
#   theme(legend.position = "FALSE") +
#   labs(title = "Sexo dos candidatos da região Sudeste do Enem 2016")
# g20

#base dos aprovados
sexo.1 <- base %>% 
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
           Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
           Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") %>% 
  group_by(SEXO) %>% 
  summarise(n = n()) %>% 
  mutate(prop = round(n*100/sum(n), 1),
         rot.ypos = cumsum(prop) - 0.5*prop, 
         rotulo = paste0(SEXO, "\n", round(prop,2), "%"))

# Criando um gráfico de setores com rótulos
g21 <- ggplot(sexo.1, 
             aes(x = "", 
                 y = prop, 
                 fill = order(SEXO))) +
  geom_bar(width = 1, 
           stat = "identity", 
           color = "black",
           fill = c("tomato", "#21908CFF")) +
  geom_text(aes(y = rot.ypos, label = rotulo), 
            color = "black") +
  coord_polar("y", 
              start = 0, 
              direction = -1) +
  theme_void() +
  theme(legend.position = "FALSE") +
  labs(title = "Sexo dos candidatos da região Sudeste do Enem 2016 Aprovados")
g21

#sexo não aprovados e não concorridos
sexo.2 <- base %>% 
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
           Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
           Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") %>% 
  group_by(SEXO) %>% 
  summarise(n = n()) %>% 
  mutate(prop = round(n*100/sum(n), 1),
         rot.ypos = cumsum(prop) - 0.5*prop, 
         rotulo = paste0(SEXO, "\n", round(prop,2), "%"))

# Criando um gráfico de setores com rótulos
g22 <- ggplot(sexo.2, 
             aes(x = "", 
                 y = prop, 
                 fill = order(SEXO))) +
  geom_bar(width = 1, 
           stat = "identity", 
           color = "black",
           fill = c("tomato", "#21908CFF")) +
  geom_text(aes(y = rot.ypos, label = rotulo), 
            color = "black") +
  coord_polar("y", 
              start = 0, 
              direction = -1) +
  theme_void() +
  theme(legend.position = "FALSE") +
  labs(title = "Sexo dos candidatos da região Sudeste do Enem 2016 Aprovados")
g22

```

```{r}
#Gráfico treemap para escolaridade da mãe dos candidatos para os aprovados em pedagogia
cont_ESCOL_MAE <- base |>
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
         Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
         Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") |>
  count(ESCOL_MAE)

cont_ESCOL_MAE$prop <- cont_ESCOL_MAE$n/sum(cont_ESCOL_MAE$n) * 100

cont_ESCOL_MAE$rotulo <- paste0(round(cont_ESCOL_MAE$prop,2), "%")

cont_ESCOL_MAE |> 
  mutate(ESCOL_MAE= ordered(ESCOL_MAE,levels=c("A","B","C","D","E","F","G","H"),
                        labels=c("Sem estudo \n0.79%","Até 5º ano do EF\n incompleto \n6.93%","Até 9º ano do EF\n incompleto \n9.44%","Até EM incompleto \n10.28%","Completou o EM,\n mas não completou a Faculdade \n34.29%","Completou a Faculdade,\n mas não completou a Pós-graduação \n21.67%","Completou a Pós-graduação \n15.26%","Não sei \n1.34%"))) |> 
  ggplot(aes(fill = ESCOL_MAE, 
           area = n, label = ESCOL_MAE)) +
  geom_treemap() + 
  geom_treemap_text(colour = "black", 
                    place = "centre") +
  scale_fill_brewer(palette = "Set3" ) +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(title="Perfil dos candidatos segundo escolaridade da mãe",
       subtitle="Dados referentes aos candidatos do ENEM 2016 aprovados em pedagogia na UFF em 2017") +   theme_classic()
```

```{r}
#Gráfico treemap para escolaridade da mãe dos candidatos (população geral)
cont_ESCOL_MAE <- base |>
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
         Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
         Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") |>
  count(ESCOL_MAE)

cont_ESCOL_MAE$prop <- cont_ESCOL_MAE$n/sum(cont_ESCOL_MAE$n) * 100

cont_ESCOL_MAE$rotulo <- paste0(round(cont_ESCOL_MAE$prop,2), "%")

cont_ESCOL_MAE |> 
  mutate(ESCOL_MAE= ordered(ESCOL_MAE,levels=c("A","B","C","D","E","F","G","H"),
                        labels=c("Sem estudo \n3.32%","Até 5º ano do EF\n incompleto \n17.84%","Até 9º ano do EF\n incompleto \n16.69%","Até EM incompleto \n15.74%","Completou o EM,\n mas não completou a Faculdade \n31.55%","Completou a Faculdade,\n mas não completou a Pós-graduação \n7.5%","Completou a Pós-graduação \n4.07%","Não sei \n3.29%"))) |> 
  ggplot(aes(fill = ESCOL_MAE, 
           area = n, label = ESCOL_MAE)) +
  geom_treemap() + 
  geom_treemap_text(colour = "black", 
                    place = "centre") +
  scale_fill_brewer(palette = "Set3" ) +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(title="Porcentagem de candidatos segundo escolaridade da mãe",
       subtitle="Dados referentes aos candidatos do ENEM 2016 (população geral)") + theme_classic()
```

```{r}
#Histograma da idade dos candidatos para os aprovados em pedagogia
base |> 
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
           Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
           Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") |> 
  ggplot(mapping = aes(x = IDADE)) +
  geom_histogram(fill= "orange", col="white")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(y= "Frequência", x="Idade",
       title="Perfil dos candidatos segundo a idade",
       subtitle="Dados referentes aos candidatos do ENEM 2016 aprovados em pedagogia na UFF em 2017") +   theme_classic()

```

```{r}
#Histograma da idade dos candidatos (população geral)
base |> 
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
           Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
           Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") |> 
  ggplot(mapping = aes(x = IDADE)) +
  geom_histogram(fill= "darkred", col="white")+
  scale_y_continuous(label = scales::label_number(big.mark = ".",
                                                  decimal.mark = ",")) +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(y= "Frequência", x="Idade",
       title="Perfil dos candidatos segundo a idade",
       subtitle="Dados referentes aos candidatos do ENEM 2016 (população geral)") +   theme_classic()

```

```{r}
#Boxplot do número de pessoas residentes na casa do candidato para os aprovados em pedagogia
base |> 
  filter(Situação_A1.1=="Aprovado"|
           Situação_A2.1=="Aprovado" |
           Situação_A6.1=="Aprovado"|
           Situação_A7.1=="Aprovado" | 
           Situação_B.1=="Aprovado"|
           Situação_A1.2=="Aprovado"|
           Situação_A2.2=="Aprovado" |
           Situação_A6.2=="Aprovado"|
           Situação_A7.2=="Aprovado" | 
           Situação_B.2=="Aprovado") |> 
  ggplot(mapping = aes(x = MORA)) +
  geom_boxplot()+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(y= "Frequência", x="Número de pessoas residentes na casa",
       title="Perfil dos candidatos segundo o número de pessoas residentes em sua casa",
       subtitle="Dados referentes aos candidatos do ENEM 2016 aprovados em pedagogia na UFF em 2017") +   theme_classic()

```

```{r}
#Boxplot do número de pessoas residentes na casa do candidato (população geral)
base |> 
  filter(Situação_A1.1!="Aprovado",
           Situação_A2.1!="Aprovado" ,
           Situação_A6.1!="Aprovado",
           Situação_A7.1!="Aprovado" , 
           Situação_B.1!="Aprovado",
           Situação_A1.2!="Aprovado",
           Situação_A2.2!="Aprovado" ,
           Situação_A6.2!="Aprovado",
           Situação_A7.2!="Aprovado" , 
           Situação_B.2!="Aprovado") |> 
  ggplot(mapping = aes(y = MORA)) +
  geom_boxplot()+
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12)) +
  labs(y= "Frequência", x="Número de pessoas residentes na casa",
       title="Perfil dos candidatos segundo o número de pessoas residentes em sua casa",
       subtitle="Dados referentes aos candidatos do ENEM 2016 (população geral)") + 
  theme_classic()

```
